version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: hola
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo pre adios
      - run: echo post adios

workflows:
  hello:
    jobs:
      - saluda
      - despidete
  workflow2:
      - saluda
      - despidete:
          requires:
            - saluda
